name: Update Docker Hub Description

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - '.github/workflows/dockerhub-description.yml'

jobs:
  dockerHubDescription:
    name: Sync Docker Hub description with GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: ${{ github.repository }}
          short-description: ${{ github.event.repository.description }}
