name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/juicenet-cli
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for changelog

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.13'

      - name: Build project for distribution
        run: uv build

      - name: Generate a changelog
        run: >-
          uvx git-cliff --config .github/cliff-template.toml
          --github-repo "${GH_REPO}"
          --github-token "${GH_TOKEN}"
          --latest --strip header
          --output "CHANGELOG.md"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: "CHANGELOG.md"
          draft: false
          prerelease: false

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
