name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: 1
  UV_LOCKED: 1

jobs:
  release:
    name: Release
    environment:
      name: pypi
      url: https://pypi.org/project/juicenet-cli
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 0 # Important for changelog

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          enable-cache: false
          python-version: "3.13"

      - name: Build
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0

      - name: Generate a changelog
        run: >-
          uvx git-cliff --config .github/cliff-template.toml
          --github-repo "${GH_REPO}"
          --github-token "${GH_TOKEN}"
          --latest --strip header
          --output "CHANGELOG.md"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}

      - name: Create Release
        run: gh release create "${GH_REF_NAME}" -F "CHANGELOG.md" --fail-on-no-commits
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REF_NAME: ${{ github.ref_name }}
