name: Smoke Test

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/tests.yml'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/tests.yml'
  workflow_dispatch:
  workflow_call:


permissions:
  contents: read

env:
  FORCE_COLOR: 1
  UV_LOCKED: 1

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  smoke-test:
    name: Smoke Test
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6.7.0
        with:
          enable-cache: false
          python-version: ${{ matrix.python-version }}

      - name: Run smoke test
        run: |
          uv run juicenet --help
          uv run juicenet --version
